CPP = g++
OPTS =  -I -pthread  -lglut -lGLU -g -lsfml-audio

all:
	$(CPP) -Wall -lGL -o game main.cpp imageloader.cpp $(OPTS) 
	

clean:
	rm game
#../bin/linux-gcc/libIrrKlang.so ../bin/linux-gcc/ikpMP3.so
#"../include" -L"/usr/lib"
